[project]
name = "flask-commands"
version = "0.3.10"
description = "A set of command line tools that help you scaffold out your flask application quickly."
authors = [
    {name = "Drew Butcher",email = "drewlbutcher@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "Flask>=3.1,<4",
    "click (>=8.3.1,<9.0.0)",
    "python-dotenv>=1.0,<2",
]
include = [
    { path = "flask_commands/project", format = "sdist" },
    { path = "flask_commands/project", format = "wheel" },
    { path = "flask_commands/project_no_db", format = "sdist" },
    { path = "flask_commands/project_no_db", format = "wheel" }
]

[project.entry-points."flask.commands"]
new = "flask_commands.commands.new:new"
commands = "flask_commands.commands.meta:commands"
"make:model" = "flask_commands.commands.model:make_model"
"make:view" = "flask_commands.commands.view:make_view"
"make:controller" = "flask_commands.commands.controller:make_controller"


[project.optional-dependencies]
docs = [
    "sphinx (<9)",
    "sphinx-copybutton",
    "pydata-sphinx-theme (>=0.16.1,<0.17.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "coverage (>=7.13.0,<8.0.0)",
    "sphinx-autobuild (>=2025.8.25,<2026.0.0)",
    "pydata-sphinx-theme (>=0.16.1,<0.17.0)",
    "pytest-cov (>=7.1.0,<8.0.0)"
]

[tool.coverage.run]
source = ["flask_commands"]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 70

[project.urls]
Homepage = "https://flask-commands.readthedocs.io/en/latest/"
Repository = "https://github.com/drewbutcher/flask-commands"
Issues = "https://github.com/drewbutcher/flask-commands/issues"
